#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
Name     : qt6quick3d
Version  : 6.6.1
Release  : 4
URL      : https://download.qt.io/official_releases/qt/6.6/6.6.1/submodules/qtquick3d-everywhere-src-6.6.1.tar.xz
Source0  : https://download.qt.io/official_releases/qt/6.6/6.6.1/submodules/qtquick3d-everywhere-src-6.6.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0 MIT
BuildRequires : assimp-dev
BuildRequires : buildreq-cmake
BuildRequires : mesa-dev
BuildRequires : qt6base-dev
BuildRequires : qt6declarative-dev
BuildRequires : qt6shadertools-dev
BuildRequires : qtbase-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
==================
INSTALLATION GUIDE
==================
------------
Dependencies
------------

%prep
%setup -q -n qtquick3d-everywhere-src-6.6.1
cd %{_builddir}/qtquick3d-everywhere-src-6.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703008297
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1703008297
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6quick3d
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/b073f11f0c81a95ab5e32aa6b5d23a5955a95274 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/LICENSES/GFDL-1.3-no-invariants-only.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/assimp/LICENSE %{buildroot}/usr/share/package-licenses/qt6quick3d/8f2903ca181caa4ee147cd6646151d83f0d72eb7 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/assimp/src/LICENSE %{buildroot}/usr/share/package-licenses/qt6quick3d/4575cfb8457432392d1b932fe255751b487d7d8a || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/assimp/src/contrib/poly2tri/LICENSE %{buildroot}/usr/share/package-licenses/qt6quick3d/3c4a0cf53278b001dd25ca8dea8d543fc0374181 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/assimp/src/contrib/rapidjson/license.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/47ab05791f28173ad2b82f25c2b5c7fc06252b4d || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/embree/LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/meshoptimizer/LICENSE.md %{buildroot}/usr/share/package-licenses/qt6quick3d/9483603dbfc93cf906fe60cee768a936bc3b6055 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/tinyexr/LICENSE %{buildroot}/usr/share/package-licenses/qt6quick3d/0f547666cbbd9ee21ced13884bfdcf7984e87eed || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/3rdparty/xatlas/LICENSE %{buildroot}/usr/share/package-licenses/qt6quick3d/e2d8be2cbcf8054d6ac6fd2adb453c7b34142c86 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/helpers/GODOT_LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/c1abd499f2172708878718db8fb32186736fd799 || :
cp %{_builddir}/qtquick3d-everywhere-src-%{version}/src/runtimerender/GODOT_LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6quick3d/c1abd499f2172708878718db8fb32186736fd799 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
